name:Build CI - windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - name: Build 
      run: Password Protected Notes Taker -c 3_Implementation
    
